/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppManager: typeof import('./src/components/AppManager.vue')['default']
    CliTerminalView: typeof import('./src/components/CliTerminalView.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    CustomEnvEditor: typeof import('./src/components/CustomEnvEditor.vue')['default']
    DshManager: typeof import('./src/components/DshManager.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ExternalSitesManager: typeof import('./src/components/ExternalSitesManager.vue')['default']
    LogViewer: typeof import('./src/components/LogViewer.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    MenuPanelContent: typeof import('./src/components/MenuPanelContent.vue')['default']
    OpenclawManager: typeof import('./src/components/OpenclawManager.vue')['default']
    PageManager: typeof import('./src/components/PageManager.vue')['default']
    PageSwitcher: typeof import('./src/components/PageSwitcher.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    SetupGate: typeof import('./src/components/SetupGate.vue')['default']
    TerminalDrawer: typeof import('./src/components/TerminalDrawer.vue')['default']
    TopProgressBar: typeof import('./src/components/TopProgressBar.vue')['default']
    WindowControls: typeof import('./src/components/WindowControls.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
