/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppManager: typeof import('./src/components/panels/AppManager.vue')['default']
    CliTerminalView: typeof import('./src/components/terminal/CliTerminalView.vue')['default']
    CommandPalette: typeof import('./src/components/shell/CommandPalette.vue')['default']
    CustomEnvEditor: typeof import('./src/components/env/CustomEnvEditor.vue')['default']
    DshManager: typeof import('./src/components/panels/DshManager.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElOptionGroup: typeof import('element-plus/es')['ElOptionGroup']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/base/EmptyState.vue')['default']
    EnvDirChoice: typeof import('./src/components/env/EnvDirChoice.vue')['default']
    ExternalSitesManager: typeof import('./src/components/panels/ExternalSitesManager.vue')['default']
    LogTimeline: typeof import('./src/components/monitor/LogTimeline.vue')['default']
    LogViewer: typeof import('./src/components/monitor/LogViewer.vue')['default']
    McpManager: typeof import('./src/components/panels/McpManager.vue')['default']
    MenuBar: typeof import('./src/components/layout/classic/MenuBar.vue')['default']
    MenuPanelContent: typeof import('./src/components/panels/MenuPanelContent.vue')['default']
    NetIndicator: typeof import('./src/components/shell/NetIndicator.vue')['default']
    OpenclawManager: typeof import('./src/components/panels/OpenclawManager.vue')['default']
    PageManager: typeof import('./src/components/panels/PageManager.vue')['default']
    PageSwitcher: typeof import('./src/components/shell/PageSwitcher.vue')['default']
    QQShell: typeof import('./src/components/layout/qq/QQShell.vue')['default']
    ResourceTrend: typeof import('./src/components/monitor/ResourceTrend.vue')['default']
    SettingsPanel: typeof import('./src/components/panels/SettingsPanel.vue')['default']
    SetupGate: typeof import('./src/components/shell/SetupGate.vue')['default']
    TerminalDrawer: typeof import('./src/components/terminal/TerminalDrawer.vue')['default']
    TopProgressBar: typeof import('./src/components/shell/TopProgressBar.vue')['default']
    WindowControls: typeof import('./src/components/shell/WindowControls.vue')['default']
    WorkspaceContext: typeof import('./src/components/panels/WorkspaceContext.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
